sudo: false
language: ruby
rvm:
  - 2.3.0
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database appwars_test;' -U postgres
  - bundle exec rake db:migrate --trace
addons:
  code_climate:
    repo_token: ea760e66c8ad94eca379a7e1e99b3f13f451720cf474100e006a3ffb08b8831f
deploy:
  provider: heroku
  api_key:
    secure: c9SnQJxSZr/orLYzr5RFjWWI//2XDYScEYCwwMy8Xa63jy7VPlCLOX0Q8LY7+A4eA4JtHnVmnwcVWtpZ62/9WxLKJFSL49lDSv/uxn5SFV40lgi3EgGA+tZjxbYjFWyYmiHt8KDZuo6LcuOZh4VBoXUeTfAhVsl793lrAcptbvCPxM+BvcqsWfzoo3kfCS7QRQRlS5l6rtBw6hfrp+4hlHMg6M/xue7HOMGAbhx6v0gQHYIsA2ILYuajEoVBE1OwgHIHRqwNaKpPA81LDLOmyk3oij0xnXlUM63XMMm1Ra4EYnVFJkx+c92YTC6NLn6c5yQYWKQCLpxDSH2ThT6aJ4x4J47nRyRpKBiu96qJXk5G3YlWOjiy1VAX2kxiXXVxikeYjvqj3z1ygAngbsfarTfN7SUOZiDXQUIxMF4I59WLkc4ckZwgKVS+tZIg0IZ10MsWvKbDkQw/35+ppx8SEgT99/1tbuTJY4Jj5tGG9Qu9vXmXhPn54SXifTxo1xxCiBZllX/l6ecSExfK2eaqNu8OYanIgal5lHscDbP20yNjKDVeiBKP2jPZ+2aKIswBtogEXfPpgHl7RL6bQLa+5rsxXDReYhbsa+0S8Yg6iZy90EjUb6tCu+fa0gxek+1yFEuIiksc1bmVrbwm9vH366xVeftkuvMVN5hwwCn7uU8=
  app: appwars
  on:
    repo: fantasygame/appwars
  run: "rake db:migrate"
